ALTER TABLE tb_isu_strategis_opd 
ADD COLUMN potensi_perangkat_daerah VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN isu_klhs VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN isu_global VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN isu_nasional VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN isu_regional VARCHAR(255) NOT NULL DEFAULT '';