CREATE TABLE tb_permasalahan_terpilih(
    id INT PRIMARY KEY AUTO_INCREMENT,
    permasalahan_opd_id INT NOT NULL,
    kode_opd VARCHAR(255) NOT NULL,
    tahun VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;