CREATE TABLE tb_jumlah_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_data_dukung INT NOT NULL,
    tahun VARCHAR(255) NOT NULL,
    jumlah DOUBLE PRECISION,
    satuan VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;