// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"permasalahanService/app"
	"permasalahanService/controller"
	"permasalahanService/repository"
	"permasalahanService/service"
)

import (
	_ "permasalahanService/docs"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	permasalahanRepositoryImpl := repository.NewPermasalahanRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	permasalahanServiceImpl := service.NewPermasalahanServiceImpl(permasalahanRepositoryImpl, db, validate)
	permasalahanControllerImpl := controller.NewPermasalahanControllerImpl(permasalahanServiceImpl)
	permasalahanTerpilihRepositoryImpl := repository.NewPermasalahanTerpilihRepositoryImpl()
	permasalahanTerpilihServiceImpl := service.NewPermasalahanTerpilihServiceImpl(permasalahanTerpilihRepositoryImpl, permasalahanRepositoryImpl, db, validate)
	permasalahanTerpilihControllerImpl := controller.NewPermasalahanTerpilihControllerImpl(permasalahanTerpilihServiceImpl)
	isuStrategisRepositoryImpl := repository.NewIsuStrategisRepositoryImpl()
	isuStrategisServiceImpl := service.NewIsuStrategisServiceImpl(isuStrategisRepositoryImpl, permasalahanRepositoryImpl, permasalahanTerpilihRepositoryImpl, db, validate)
	isuStrategisControllerImpl := controller.NewIsuStrategisControllerImpl(isuStrategisServiceImpl)
	echoEcho := app.NewRouter(permasalahanControllerImpl, permasalahanTerpilihControllerImpl, isuStrategisControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var permasalahanSet = wire.NewSet(repository.NewPermasalahanRepositoryImpl, wire.Bind(new(repository.PermasalahanRepository), new(*repository.PermasalahanRepositoryImpl)), service.NewPermasalahanServiceImpl, wire.Bind(new(service.PermasalahanService), new(*service.PermasalahanServiceImpl)), controller.NewPermasalahanControllerImpl, wire.Bind(new(controller.PermasalahanController), new(*controller.PermasalahanControllerImpl)))

var permasalahanTerpilihSet = wire.NewSet(repository.NewPermasalahanTerpilihRepositoryImpl, wire.Bind(new(repository.PermasalahanTerpilihRepository), new(*repository.PermasalahanTerpilihRepositoryImpl)), service.NewPermasalahanTerpilihServiceImpl, wire.Bind(new(service.PermasalahanTerpilihService), new(*service.PermasalahanTerpilihServiceImpl)), controller.NewPermasalahanTerpilihControllerImpl, wire.Bind(new(controller.PermasalahanTerpilihController), new(*controller.PermasalahanTerpilihControllerImpl)))

var isuStrategisSet = wire.NewSet(repository.NewIsuStrategisRepositoryImpl, wire.Bind(new(repository.IsuStrategisRepository), new(*repository.IsuStrategisRepositoryImpl)), service.NewIsuStrategisServiceImpl, wire.Bind(new(service.IsuStrategisService), new(*service.IsuStrategisServiceImpl)), controller.NewIsuStrategisControllerImpl, wire.Bind(new(controller.IsuStrategisController), new(*controller.IsuStrategisControllerImpl)))
