// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/permasalahan": {
            "post": {
                "description": "Create a new permasalahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permasalahan Service"
                ],
                "summary": "Create Permasalahan",
                "parameters": [
                    {
                        "description": "Create Permasalahan",
                        "name": "permasalahan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PermasalahanCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/permasalahan/{id}": {
            "get": {
                "description": "FindById an existing permasalahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permasalahan Service"
                ],
                "summary": "FindById Permasalahan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Permasalahan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a permasalahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permasalahan Service"
                ],
                "summary": "Update Permasalahan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Permasalahan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Permasalahan",
                        "name": "permasalahan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PermasalahanUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing permasalahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permasalahan Service"
                ],
                "summary": "Delete Permasalahan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Permasalahan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/permasalahan/{kode_opd}/{tahun}": {
            "get": {
                "description": "FindAll an existing permasalahan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permasalahan Service"
                ],
                "summary": "FindAll Permasalahan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kode_opd",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tahun",
                        "name": "tahun",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.PermasalahanCreateRequest": {
            "description": "Request Permasalahan Create",
            "type": "object",
            "required": [
                "jenis_masalah",
                "kode_opd",
                "level_pohon",
                "nama_opd",
                "permasalahan",
                "pokin_id",
                "tahun"
            ],
            "properties": {
                "jenis_masalah": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "level_pohon": {
                    "type": "integer"
                },
                "nama_opd": {
                    "type": "string"
                },
                "permasalahan": {
                    "type": "string"
                },
                "pokin_id": {
                    "type": "integer"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.PermasalahanUpdateRequest": {
            "description": "Update Request Permasalahan",
            "type": "object",
            "required": [
                "kode_opd",
                "level_pohon",
                "nama_opd",
                "permasalahan",
                "tahun"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "level_pohon": {
                    "type": "integer"
                },
                "nama_opd": {
                    "type": "string"
                },
                "permasalahan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${HOST}:${PORT}",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Permasalahan & Isu Strategis Service API",
	Description:      "API For Permasalahan & Isu Strategis Services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
